import { useState, useEffect } from 'react'
import { useSearchParams, useNavigate } from 'react-router-dom'
import { API_BASE_URL } from '../config/api'
import { RcDocIllustration } from '../components/Illustrations'

export default function VehicleInfo() {
  const [searchParams] = useSearchParams()
  const navigate = useNavigate()
  const [vehicleNumber, setVehicleNumber] = useState(searchParams.get('vehicle') || '')
  const [vehicle, setVehicle] = useState(null)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState('')

  useEffect(() => {
    const v = searchParams.get('vehicle')
    if (v) {
      setVehicleNumber(v)
      fetchVehicleInfo(v)
    }
  }, [searchParams])

  const fetchVehicleInfo = async (number) => {
    if (!number.trim()) return
    setLoading(true)
    setError('')
    setVehicle(null)
    try {
      const response = await fetch(`${API_BASE_URL}/api/external/vehicle/${encodeURIComponent(number.trim())}`)
      const data = await response.json()
      if (data.success && data.vehicle?.response) {
        const v = data.vehicle.response
        setVehicle({
          number: v.license_plate,
          owner: maskOwnerName(v.owner_name),
          fuelType: v.fuel_type || 'N/A',
          vehicleClass: v.class,
          type: v.class?.includes('Scooter') || v.class?.includes('2W') ? 'Bike' : 'Car',
          insuranceExpiry: formatDateString(v.insurance_expiry),
          registrationDate: formatDateString(v.registration_date),
          rto: 'Lucknow, UP',
        })
      } else {
        setError(data.message || 'Vehicle not found')
      }
    } catch {
      setError('Network error. Please try again.')
    } finally {
      setLoading(false)
    }
  }

  const maskOwnerName = (name) => {
    if (!name) return 'Unknown'
    const parts = name.split(' ')
    if (parts.length === 1) return parts[0]
    return parts.map((p, i) => i === 0 ? p : (p[0] + '***')).join(' ')
  }

  const formatDateString = (dateStr) => {
    if (!dateStr || dateStr === '1900-01-01') return 'N/A'
    try {
      return new Date(dateStr).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' })
    } catch {
      return dateStr
    }
  }

  const handleSearch = (e) => {
    e.preventDefault()
    if (vehicleNumber.trim()) {
      navigate(`/vehicle-info?vehicle=${encodeURIComponent(vehicleNumber.trim())}`)
      fetchVehicleInfo(vehicleNumber.trim())
    }
  }

  const handleDownloadRC = () => {
    if (!vehicle) return

    const html = `
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="utf-8" />
        <title>RC Details - ${vehicle.number}</title>
        <style>
          * { box-sizing: border-box; }
          body { font-family: Inter, Arial, sans-serif; background: #f1f5f9; margin: 0; padding: 24px; color: #0f172a; }
          .card { max-width: 720px; margin: 0 auto; background: #fff; border-radius: 16px; border: 1px solid #e2e8f0; box-shadow: 0 8px 24px -12px rgba(15,23,42,.2); padding: 24px; }
          .title { font-size: 28px; font-weight: 800; color: #2563eb; margin: 8px 0 0; }
          .sub { color: #64748b; font-size: 13px; margin-bottom: 20px; }
          .badge { display: inline-block; background: #ecfdf5; color: #047857; font-weight: 700; font-size: 11px; border-radius: 9999px; padding: 6px 10px; }
          .row { display: flex; justify-content: space-between; gap: 16px; border-top: 1px solid #f1f5f9; padding: 12px 0; }
          .label { color: #64748b; font-size: 13px; }
          .value { color: #0f172a; font-size: 13px; font-weight: 700; text-align: right; }
          .foot { margin-top: 20px; color: #94a3b8; font-size: 12px; text-align: center; }
          @media print { body { background: #fff; padding: 0; } .card { box-shadow: none; border: none; } }
        </style>
      </head>
      <body>
        <div class="card">
          <span class="badge">Verified</span>
          <h1 class="title">${vehicle.number}</h1>
          <p class="sub">Registration Number</p>
          <div class="row"><span class="label">Owner Name</span><span class="value">${vehicle.owner}</span></div>
          <div class="row"><span class="label">Fuel Type</span><span class="value">${vehicle.fuelType}</span></div>
          <div class="row"><span class="label">Vehicle Type</span><span class="value">${vehicle.type}</span></div>
          <div class="row"><span class="label">Insurance Validity</span><span class="value">${vehicle.insuranceExpiry}</span></div>
          <div class="row"><span class="label">Registration Date</span><span class="value">${vehicle.registrationDate}</span></div>
          <div class="row"><span class="label">RTO</span><span class="value">${vehicle.rto}</span></div>
          <p class="foot">Generated by ChallanOne RC Lookup</p>
        </div>
      </body>
      </html>
    `

    const printWindow = window.open('', '_blank')
    if (!printWindow) {
      alert('Popup blocked. Please allow popups to download RC.')
      return
    }
    printWindow.document.write(html)
    printWindow.document.close()
    printWindow.focus()
    setTimeout(() => printWindow.print(), 250)
  }

  const showSearch = !vehicle && !loading
  const samples = ['UP32AB1234', 'DL1CDC5678', 'MH01EF9012']

  return (
    <div className="screen">
      <div className="screen-content">
        {/* Page title */}
        <div className="bg-gradient-to-r from-blue-50 to-sky-50 border-b border-slate-100">
          <div className="container-main py-6 md:py-10">
            <div className="flex items-center gap-3 mb-2">
              {vehicle && (
                <button onClick={() => setVehicle(null)} className="icon-btn">
                  <svg className="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                    <path strokeLinecap="round" strokeLinejoin="round" d="M15 19l-7-7 7-7" />
                  </svg>
                </button>
              )}
              <h1 className="h-section">RC Details</h1>
            </div>
            <p className="text-[14px] md:text-[15px] text-slate-500">
              {vehicle ? `Registration details for ${vehicle.number}` : 'Look up any vehicle registration details instantly'}
            </p>
          </div>
        </div>

        {showSearch && (
          <div className="container-main py-8 md:py-12">
            <div className="grid md:grid-cols-2 gap-8 md:gap-12 items-start">
              {/* Left - Search */}
              <div className="space-y-6">
                <form onSubmit={handleSearch} className="surface-card p-6 space-y-4 animate-fade-up">
                  <div>
                    <label className="field-label">Vehicle Number</label>
                    <input
                      type="text"
                      placeholder="Enter vehicle number (e.g. UP32AB1234)"
                      value={vehicleNumber}
                      onChange={(e) => setVehicleNumber(e.target.value.toUpperCase())}
                      className="input-field"
                    />
                  </div>
                  <button type="submit" disabled={loading} className="btn-primary w-full">
                    {loading ? 'Fetching...' : 'Get RC Details'}
                  </button>
                  {error && <p className="text-sm text-rose-500">{error}</p>}
                </form>

                <div className="animate-fade-up">
                  <p className="field-label">Try a sample number</p>
                  <div className="flex flex-wrap gap-2">
                    {samples.map((num) => (
                      <button
                        key={num}
                        type="button"
                        onClick={() => setVehicleNumber(num)}
                        className="rounded-full border border-slate-200 bg-white px-4 py-2 text-[13px] font-semibold text-blue-600 transition hover:bg-slate-50 active:scale-95"
                      >
                        {num}
                      </button>
                    ))}
                  </div>
                </div>
              </div>

              {/* Illustration */}
              <div className="order-first md:order-last animate-fade-up">
                <div className="hero-illu">
                  <RcDocIllustration className="w-full" />
                </div>
              </div>
            </div>
          </div>
        )}

        {error && vehicleNumber && !loading && !vehicle && (
          <div className="container-narrow py-12">
            <div className="surface-card p-8 text-center animate-fade-up">
              <div className="mx-auto mb-4 flex h-14 w-14 items-center justify-center rounded-full bg-rose-50 text-rose-500">
                <svg className="h-7 w-7" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
                </svg>
              </div>
              <h3 className="text-[18px] font-bold text-slate-900">Vehicle Not Found</h3>
              <p className="mt-1 text-[14px] text-slate-500">{error}</p>
              <button
                onClick={() => { setError(''); setVehicleNumber('') }}
                className="btn-primary mt-5"
              >
                Try Again
              </button>
            </div>
          </div>
        )}

        {loading && (
          <div className="container-narrow">
            <div className="flex flex-col items-center justify-center py-24">
              <div className="h-14 w-14 animate-spin rounded-full border-4 border-blue-100 border-t-blue-600" />
              <p className="mt-5 text-[14px] font-medium text-slate-700">Fetching vehicle details...</p>
              <p className="mt-1 text-[12px] text-slate-400">Accessing official RTO records</p>
            </div>
          </div>
        )}

        {vehicle && (
          <div className="container-main py-8 md:py-12">
            <div className="grid md:grid-cols-2 gap-8 md:gap-12">
              {/* Left - Details */}
              <div className="surface-card p-6 md:p-8 animate-fade-up">
                <span className="pill pill-success mb-4">
                  <svg className="h-3 w-3" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="3">
                    <path strokeLinecap="round" strokeLinejoin="round" d="M5 13l4 4L19 7" />
                  </svg>
                  Verified
                </span>
                <h2 className="text-[28px] md:text-[32px] font-bold text-blue-600 leading-tight">{vehicle.number}</h2>
                <p className="text-[13px] text-slate-500 mt-1">Registration Number</p>

                <div className="mt-6 divide-y divide-slate-100">
                  <DetailRow label="Owner Name" value={vehicle.owner} />
                  <DetailRow label="Fuel Type" value={vehicle.fuelType} />
                  <DetailRow label="Vehicle Type" value={vehicle.type} />
                  <DetailRow label="Insurance Validity" value={vehicle.insuranceExpiry} />
                  <DetailRow label="Registration Date" value={vehicle.registrationDate} />
                  <DetailRow label="RTO" value={vehicle.rto} />
                </div>

                <div className="flex flex-col sm:flex-row gap-3 mt-6">
                  <button onClick={handleDownloadRC} className="btn-primary flex-1">
                    <svg className="h-4 w-4" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
                    </svg>
                    Download RC
                  </button>
                  <button onClick={() => { setVehicle(null); setVehicleNumber('') }} className="btn-secondary flex-1">
                    New Search
                  </button>
                </div>
              </div>

              {/* Right - Image */}
              <div className="animate-fade-up">
                <div className="hero-illu">
                  <RcDocIllustration className="w-full" />
                </div>
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  )
}

function DetailRow({ label, value }) {
  return (
    <div className="flex items-center justify-between py-3.5">
      <span className="text-[14px] text-slate-500">{label}</span>
      <span className="text-[14px] font-semibold text-slate-900 text-right max-w-[60%] truncate">{value}</span>
    </div>
  )
}
