import { jsPDF } from 'jspdf'

const COLORS = {
  brand: [220, 38, 38],
  brandDark: [185, 28, 28],
  ink: [15, 23, 42],
  muted: [100, 116, 139],
  light: [248, 250, 252],
  border: [226, 232, 240],
  white: [255, 255, 255],
  pending: [225, 29, 72],
  pendingBg: [255, 241, 242],
  paid: [5, 150, 105],
  paidBg: [236, 253, 245],
  court: [217, 119, 6],
  courtBg: [255, 251, 235],
  slate: [51, 65, 85],
}

function formatAmount(amount) {
  return `Rs. ${Number(amount || 0).toLocaleString('en-IN')}`
}

function isCourtChallan(c) {
  return Boolean(c.isCourtChallan || c.sentToRegCourt || c.courtName)
}

function statusMeta(c) {
  if (c.status === 'PAID') {
    return { label: 'PAID', color: COLORS.paid, bg: COLORS.paidBg }
  }
  if (isCourtChallan(c)) {
    return { label: 'COURT', color: COLORS.court, bg: COLORS.courtBg }
  }
  return { label: 'PENDING', color: COLORS.pending, bg: COLORS.pendingBg }
}

function drawRoundedRect(doc, x, y, w, h, r, style = 'S') {
  doc.roundedRect(x, y, w, h, r, r, style)
}

function drawHeader(doc, pageWidth, margin) {
  // Top brand bar
  doc.setFillColor(...COLORS.brand)
  doc.rect(0, 0, pageWidth, 28, 'F')

  // Accent strip
  doc.setFillColor(...COLORS.brandDark)
  doc.rect(0, 28, pageWidth, 1.2, 'F')

  doc.setTextColor(...COLORS.white)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(18)
  doc.text('CHALLAN ONE', margin, 12)

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(8.5)
  doc.text('India\'s Trusted Challan Clearance Partner', margin, 18.5)

  doc.setFont('helvetica', 'bold')
  doc.setFontSize(11)
  doc.text('CHALLAN REPORT', pageWidth - margin, 12, { align: 'right' })

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(8)
  doc.text(new Date().toLocaleString('en-IN', {
    day: '2-digit',
    month: 'short',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  }), pageWidth - margin, 18.5, { align: 'right' })
}

function drawFooter(doc, pageWidth, pageHeight, margin, pageNum, totalPages) {
  doc.setDrawColor(...COLORS.border)
  doc.setLineWidth(0.3)
  doc.line(margin, pageHeight - 14, pageWidth - margin, pageHeight - 14)

  doc.setTextColor(...COLORS.muted)
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(7.5)
  doc.text('Generated by Challan One  •  Official data for reference only  •  www.challanone.com', margin, pageHeight - 8)
  doc.text(`Page ${pageNum} of ${totalPages}`, pageWidth - margin, pageHeight - 8, { align: 'right' })
}

/**
 * Download a polished PDF listing all challans for a vehicle.
 * @param {{ number: string, owner?: string, vehicleType?: string, isVerified?: boolean }} vehicle
 * @param {Array} challans - normalized challan records
 */
export function downloadChallansPdf(vehicle, challans = []) {
  const doc = new jsPDF({ unit: 'mm', format: 'a4', compress: true })
  const margin = 12
  const pageWidth = doc.internal.pageSize.getWidth()
  const pageHeight = doc.internal.pageSize.getHeight()
  const contentWidth = pageWidth - margin * 2
  let y = 36

  const pending = challans.filter((c) => c.status !== 'PAID')
  const paid = challans.filter((c) => c.status === 'PAID')
  const court = challans.filter((c) => isCourtChallan(c) && c.status !== 'PAID')
  const pendingTotal = pending.reduce((s, c) => s + (c.amount || 0), 0)
  const paidTotal = paid.reduce((s, c) => s + (c.amount || 0), 0)
  const grandTotal = challans.reduce((s, c) => s + (c.amount || 0), 0)

  const ensureSpace = (needed) => {
    if (y + needed > pageHeight - 20) {
      doc.addPage()
      y = 36
      drawHeader(doc, pageWidth, margin)
      return true
    }
    return false
  }

  // ── Page 1 header ──
  drawHeader(doc, pageWidth, margin)

  // ── Title ──
  doc.setTextColor(...COLORS.ink)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(15)
  doc.text('Vehicle Challan Summary', margin, y)
  y += 7

  // ── Vehicle info card ──
  doc.setFillColor(...COLORS.light)
  doc.setDrawColor(...COLORS.border)
  drawRoundedRect(doc, margin, y, contentWidth, 22, 2.5, 'FD')

  doc.setFillColor(...COLORS.brand)
  doc.roundedRect(margin + 3, y + 4, 18, 14, 1.5, 1.5, 'F')
  doc.setTextColor(...COLORS.white)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(6)
  doc.text('IND', margin + 12, y + 9, { align: 'center' })
  doc.setFontSize(8)
  doc.text((vehicle?.number || 'N/A').slice(0, 10), margin + 12, y + 14.5, { align: 'center' })

  doc.setTextColor(...COLORS.ink)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(13)
  doc.text(vehicle?.number || 'N/A', margin + 26, y + 8)

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(8.5)
  doc.setTextColor(...COLORS.slate)
  const ownerLine = [vehicle?.owner, vehicle?.vehicleType || 'Private Vehicle']
    .filter(Boolean)
    .join('  •  ')
  doc.text(ownerLine || 'Vehicle details', margin + 26, y + 14)

  if (vehicle?.isVerified) {
    doc.setFillColor(...COLORS.paidBg)
    doc.setDrawColor(...COLORS.paid)
    drawRoundedRect(doc, pageWidth - margin - 28, y + 6.5, 24, 8, 2, 'FD')
    doc.setTextColor(...COLORS.paid)
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(7)
    doc.text('VERIFIED', pageWidth - margin - 16, y + 11.8, { align: 'center' })
  }

  y += 28

  // ── Stats cards ──
  const stats = [
    { label: 'TOTAL', value: String(challans.length), sub: formatAmount(grandTotal), accent: COLORS.ink },
    { label: 'PENDING', value: String(pending.length), sub: formatAmount(pendingTotal), accent: COLORS.pending },
    { label: 'PAID', value: String(paid.length), sub: formatAmount(paidTotal), accent: COLORS.paid },
    { label: 'COURT', value: String(court.length), sub: 'Action needed', accent: COLORS.court },
  ]
  const gap = 3
  const cardW = (contentWidth - gap * 3) / 4

  stats.forEach((stat, i) => {
    const x = margin + i * (cardW + gap)
    doc.setFillColor(...COLORS.white)
    doc.setDrawColor(...COLORS.border)
    drawRoundedRect(doc, x, y, cardW, 20, 2, 'FD')
    doc.setFillColor(...stat.accent)
    doc.rect(x, y, 1.4, 20, 'F')

    doc.setTextColor(...COLORS.muted)
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(6.5)
    doc.text(stat.label, x + 4, y + 5.5)

    doc.setTextColor(...stat.accent)
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(12)
    doc.text(stat.value, x + 4, y + 12)

    doc.setTextColor(...COLORS.slate)
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(6.5)
    doc.text(stat.sub, x + 4, y + 17)
  })

  y += 26

  // ── Amount highlight ──
  doc.setFillColor(...COLORS.brand)
  drawRoundedRect(doc, margin, y, contentWidth, 14, 2.5, 'F')
  doc.setTextColor(...COLORS.white)
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(8)
  doc.text('TOTAL OUTSTANDING / GRAND TOTAL', margin + 5, y + 5.5)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(14)
  doc.text(formatAmount(grandTotal), pageWidth - margin - 5, y + 9.5, { align: 'right' })
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(8)
  doc.text(`${challans.length} challan${challans.length === 1 ? '' : 's'} listed below`, margin + 5, y + 11)

  y += 20

  // ── Section title ──
  doc.setTextColor(...COLORS.ink)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(11)
  doc.text('Detailed Challan List', margin, y)
  y += 3
  doc.setDrawColor(...COLORS.brand)
  doc.setLineWidth(0.8)
  doc.line(margin, y, margin + 28, y)
  y += 6

  if (challans.length === 0) {
    doc.setFillColor(...COLORS.light)
    drawRoundedRect(doc, margin, y, contentWidth, 18, 2, 'F')
    doc.setTextColor(...COLORS.muted)
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(10)
    doc.text('No challans found for this vehicle.', margin + 5, y + 11)
  }

  // ── Challan cards ──
  challans.forEach((c, index) => {
    const offence =
      c.offenceDetails && c.offenceDetails !== 'N/A'
        ? c.offenceDetails
        : c.type || 'Traffic Violation'
    const offenceLines = doc.splitTextToSize(offence, contentWidth - 14)
    const locationLines = doc.splitTextToSize(`Location: ${c.location || 'N/A'}`, contentWidth - 14)
    const courtLines =
      c.courtName || c.courtAddress
        ? doc.splitTextToSize(
            `Court: ${[c.courtName, c.courtAddress].filter(Boolean).join(' — ')}`,
            contentWidth - 14
          )
        : []

    const cardH =
      22 +
      offenceLines.length * 3.6 +
      locationLines.length * 3.4 +
      (courtLines.length ? courtLines.length * 3.4 + 1 : 0) +
      4

    ensureSpace(cardH + 2)

    const status = statusMeta(c)

    // Card background
    doc.setFillColor(...COLORS.white)
    doc.setDrawColor(...COLORS.border)
    doc.setLineWidth(0.35)
    drawRoundedRect(doc, margin, y, contentWidth, cardH, 2, 'FD')

    // Left status accent
    doc.setFillColor(...status.color)
    doc.rect(margin, y, 1.8, cardH, 'F')

    // Index + notice id
    doc.setTextColor(...COLORS.ink)
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(9.5)
    doc.text(`${index + 1}.  ${c.noticeId || c.challanNumber || c.id}`, margin + 5, y + 6)

    // Status badge
    const badgeW = 18
    doc.setFillColor(...status.bg)
    drawRoundedRect(doc, pageWidth - margin - badgeW - 3, y + 2.5, badgeW, 6, 1.5, 'F')
    doc.setTextColor(...status.color)
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(6)
    doc.text(status.label, pageWidth - margin - badgeW / 2 - 3, y + 6.5, { align: 'center' })

    // Meta row
    doc.setTextColor(...COLORS.muted)
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(7.5)
    const meta = [
      `${c.date || 'N/A'}  ${c.time || ''}`.trim(),
      c.displayType || 'E-Challan',
      c.section ? `Sec. ${c.section}` : null,
    ]
      .filter(Boolean)
      .join('   ·   ')
    doc.text(meta, margin + 5, y + 11)

    // Amount
    doc.setTextColor(...COLORS.brand)
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(10)
    doc.text(formatAmount(c.amount), pageWidth - margin - 3, y + 12, { align: 'right' })

    // Divider
    doc.setDrawColor(...COLORS.border)
    doc.setLineWidth(0.2)
    doc.line(margin + 5, y + 14, pageWidth - margin - 3, y + 14)

    let ty = y + 18.5
    doc.setTextColor(...COLORS.ink)
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(8)
    doc.text(offenceLines, margin + 5, ty)
    ty += offenceLines.length * 3.6

    doc.setTextColor(...COLORS.slate)
    doc.setFontSize(7.5)
    doc.text(locationLines, margin + 5, ty)
    ty += locationLines.length * 3.4

    if (courtLines.length) {
      doc.setTextColor(...COLORS.court)
      doc.text(courtLines, margin + 5, ty)
    }

    y += cardH + 3
  })

  // ── Closing note ──
  ensureSpace(28)
  y += 2
  doc.setFillColor(254, 242, 242)
  doc.setDrawColor(...COLORS.brand)
  drawRoundedRect(doc, margin, y, contentWidth, 22, 2.5, 'FD')

  doc.setTextColor(...COLORS.brandDark)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(9)
  doc.text('Need help clearing these challans?', margin + 5, y + 7)

  doc.setTextColor(...COLORS.slate)
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(8)
  doc.text(
    'Pay securely on Challan One with UPI, cards & net banking. Instant confirmation & expert support.',
    margin + 5,
    y + 12.5
  )
  doc.text('WhatsApp: +91 92203 72007  •  support@challanone.com', margin + 5, y + 17.5)

  // Footer on all pages
  const totalPages = doc.getNumberOfPages()
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i)
    if (i > 1) drawHeader(doc, pageWidth, margin)
    drawFooter(doc, pageWidth, pageHeight, margin, i, totalPages)
  }

  const safeVehicle = (vehicle?.number || 'vehicle').replace(/[^A-Z0-9]/gi, '_')
  const dateStamp = new Date().toISOString().slice(0, 10)
  doc.save(`ChallanOne_Report_${safeVehicle}_${dateStamp}.pdf`)
}
